name: CI

on:
  schedule:
    - cron: "0 * * * *" # Run every hour
  pull_request:
  push:
    branches:
      - master
    tags: "*"

permissions:
  actions: write
  contents: read

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - run: |
          julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          julia --project=docs docs/make.jl deploy
